6
FIlipHand/EgzaminLicencjacki pull request #2
Opened 2022-05-16 13:21 UTC by Rafixese

Dobra, styknie.

2022-05-17 16:02 UTC, s-tyda approved these changes

2022-05-20 18:48 UTC, s-tyda requested changes
Trza by tu pyknąć merge po poprzedniej PR'ce

2022-05-21 08:44 UTC, FIlipHand approved these changes

2022-06-21 19:27 UTC, FIlipHand approved these changes

2022-06-21 19:27 UTC, merged